### ISSUE TITLE
NSE on ability creation

### ISSUE THREAD

**Issue by jedk1** [curz46/abilityapi#5]
```
[22:39:27 ERROR]: Could not pass event PlayerInteractEvent to AbilityAPI v0.0-ALPHA
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f9671b8-48b88ed]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f9671b8-48b88ed]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1389) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.PacketPlayInArmAnimation.a(SourceFile:32) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.PacketPlayInArmAnimation.a(SourceFile:9) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[?:1.8.0_101]
        at com.github.abilityapi.trigger.sequence.Sequence.checkDelay(Sequence.java:108) ~[?:?]
        at com.github.abilityapi.trigger.sequence.Sequence.next(Sequence.java:63) ~[?:?]
        at com.github.abilityapi.trigger.TriggerManager.handleNew(TriggerManager.java:141) ~[?:?]
        at com.github.abilityapi.trigger.TriggerManager.handle(TriggerManager.java:81) ~[?:?]
        at com.github.abilityapi.trigger.TriggerListener.onInteract(TriggerListener.java:127) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-f9671b8-48b88ed]
        ... 18 more
```

**Comment by curz46** [comment]
Is this issue still present with the new version?

**Comment by curz46** [comment]
Open another issue if the issue is still present, please :).
